#pragma once

#define GARAGE_COOKIE_1       294420452
#define GARAGE_COOKIE_2       294420453

#define GARAGE_CACHE_BUST_ID  0
#define GARAGE_OVERRIDE_ID    1
#define GARAGE_TARGET_ID      2
#define GARAGE_STATUS_ID      3

#define GARAGE_TARGET_NAME    "Garage"

#define GARAGE_POLLING_INTERVAL       2000 // 2secs
#define GARAGE_POLLING_TIMER_COOKIE   1234
